[workspace]
resolver = "3"
members = ["kernel", "libwoven"]

[features]
qemu-test = ["kernel/qemu-test"]
stage6-hotplug-test = ["qemu-test", "kernel/stage6-hotplug-test"]
network-test = ["qemu-test", "kernel/network-test"]
legacy-pic-test = ["qemu-test", "kernel/legacy-pic-test"]
stage10-4-test = ["qemu-test", "kernel/stage10-4-test"]
stage10-5-test = ["qemu-test", "kernel/stage10-5-test"]
stage10-6-test = ["qemu-test", "kernel/stage10-6-test"]
stage10-7-test = ["qemu-test", "kernel/stage10-7-test"]
stage10-8-test = ["qemu-test", "kernel/stage10-8-test"]
stage10-9-test = ["qemu-test", "kernel/stage10-9-test"]
stage11-1-test = ["qemu-test", "kernel/stage11-1-test"]
stage11-2-test = ["qemu-test", "kernel/stage11-2-test"]
stage11-3-test = ["qemu-test", "kernel/stage11-3-test"]
stage11-4-test = ["qemu-test", "kernel/stage11-4-test"]
stage11-5-test = ["qemu-test", "kernel/stage11-5-test"]
stage12-1-test = ["qemu-test", "kernel/stage12-1-test"]
stage12-2-test = ["qemu-test", "kernel/stage12-2-test"]
stage12-3-test = ["qemu-test", "kernel/stage12-3-test"]
stage12-4-test = ["qemu-test", "kernel/stage12-4-test"]
stage12-5-test = ["qemu-test", "kernel/stage12-5-test"]
stage13-1-test = ["qemu-test", "kernel/stage13-1-test"]
stage13-2-test = ["qemu-test", "kernel/stage13-2-test"]
stage13-3-test = ["qemu-test", "kernel/stage13-3-test"]
stage1-5-test = ["qemu-test", "kernel/stage1-5-test"]

[profile.dev]
panic = "abort"

[package]
name = "wovenhat-os"
version = "0.8.0"
edition = "2024"

[dependencies]
ovmf-prebuilt = "0.2.4"

[build-dependencies]
kernel = { package = "wovenhat-kernel", path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = { version = "0.11.17", default-features = false, features = ["uefi"] }

[dev-dependencies]
unicode-normalization = { version = "0.1.25", default-features = false }
[lints.rust]
warnings = "deny"
